from os import path
from hashlib import sha1
from datetime import datetime
from sqlalchemy.dialects import postgresql
import re
import pandas as pd



class Report(object):

    def __init__(self, filepath):
        self.filepath = filepath
        self.filename = path.basename(self.filepath)

        tmp = parse_filename(self.filename)
        self.report_type = tmp['report_type']
        self.start_date = tmp['report_start_date']
        self.end_date = tmp['report_end_date']
        self.report_length = tmp['report_length']
        self.advertiser = tmp['advertiser']
        self.advertiser_id = tmp['advertiser_id']

        self.og_columns = ['Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'Advertiser Total Cost',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'cost',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {}

    def githash(self):
        self.s = sha1()
        self.data = open(self.filepath, 'r')
        self.s.update(''.join([self.filename, str(len(self.data.read()))]))
        return self.s.hexdigest()

    def to_df(self, rename_cols=False):
        self.df = pd.read_csv(self.filepath,
                              usecols=self.og_columns,
                              sep='\t')
        if rename_cols:
            self.df.columns = self.rn_columns
        return self.df

    def __str__(self):
        return "%s for %s" % (self.report_type, self.advertiser)

class SiteReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Ad Format',
                           'Site',
                           'Supply Vendor',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'CreativeIsTrackable',
                           'CreativeWasViewable',
                           'App Name']
        self.rn_columns = ['advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'ad_format',
                           'site',
                           'supply_vendor',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'creative_is_trackable',
                           'creative_was_viewable',
                           'app_name']
        self.dtype = {
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'ad_format': postgresql.TEXT,
            'site': postgresql.TEXT,
            'supply_vendor': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.BIGINT,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT,
            'app_name': postgresql.BIGINT
        }

class SiteListReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Matched Site Strategy Line Id',
                           'Matched Fold Strategy Line Id',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Site Placement Adjustment Line Name',
                           'Site',
                           'Category',
                           'Site Adjustment',
                           'Fold',
                           'Fold Adjustment',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'Category Id',
                           'Category Hierarchy',
                           'Matched Site List Id',
                           'Matched Site List Name',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'matched_site_strategy_line_id',
                           'matched_fold_strategy_line_id',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'site_placement_adjustment_line_name',
                           'site',
                           'category',
                           'site_adjustment',
                           'fold',
                           'fold_adjustment',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'category_id',
                           'category_hierarchy',
                           'matched_site_list_id',
                           'matched_site_list_name',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'matched_site_strategy_line_id': postgresql.TEXT,
            'matched_fold_strategy_line_id': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'site_placement_adjustment_line_name': postgresql.TEXT,
            'site': postgresql.TEXT,
            'category': postgresql.TEXT,
            'site_adjustment': postgresql.DOUBLE_PRECISION,
            'fold': postgresql.TEXT,
            'fold_adjustment': postgresql.TEXT,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'category_id': postgresql.TEXT,
            'category_hierarchy': postgresql.TEXT,
            'matched_site_list_id': postgresql.TEXT,
            'matched_site_list_name': postgresql.TEXT,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class DataElementReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Date',
                           'Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Data Element Id',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Data Name',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'Third Party Data Brand Name',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['date',
                           'advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'data_element_id',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'data_name',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'third_party_data_brand',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'date': postgresql.TIMESTAMP,
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'data_element_id': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'data_name': postgresql.TEXT,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'third_party_data_brand': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class TimeOfDayReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Date',
                           'UTC Hour',
                           'User Hour of Week',
                           'Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['date',
                           'utc_hour',
                           'user_hour_of_week',
                           'advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'date': postgresql.TIMESTAMP,
            'utc_hour': postgresql.BIGINT,
            'user_hour_of_week': postgresql.BIGINT,
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class BrowserReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Device Type',
                           'OS Family',
                           'OS',
                           'Browser',
                           'Ad Format',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'device_type',
                           'os_family',
                           'os',
                           'browser',
                           'ad_format',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'device_type': postgresql.TEXT,
            'os_family': postgresql.TEXT,
            'os': postgresql.TEXT,
            'browser': postgresql.TEXT,
            'ad_format': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.BIGINT,
            'cta_2_rev': postgresql.BIGINT,
            'cta_3_rev': postgresql.BIGINT,
            'cta_4_rev': postgresql.BIGINT,
            'cta_5_rev': postgresql.BIGINT,
            'cta_6_rev': postgresql.BIGINT,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class AdGroupRecencyReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Audience Id',
                           'Recency Bucket Start In Minutes',
                           'RecencyBucketEndInMinutes',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Audience Name',
                           'Recency Bucket Name',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'audience_id',
                           'recency_bucket_start_in_min',
                           'recency_bucket_end_in_min',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'audience_name',
                           'recency_bucket_name',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'audience_id': postgresql.TEXT,
            'recency_bucket_start_in_minutes': postgresql.BIGINT,
            'recency_bucket_end_in_minutes': postgresql.BIGINT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'audience_name': postgresql.TEXT,
            'recency_bucket_name': postgresql.TEXT,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class PerformanceReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = [ 'Date',
                            'Advertiser Id',
                            'Campaign Id',
                            'Ad Group Id',
                            'Ad Format',
                            'Creative Id',
                            'Advertiser Name',
                            'Campaign Name',
                            'Ad Group Name',
                            'Ad Group Budget',
                            'Ad Group Daily Target',
                            'Ad Group Daily Cap',
                            'Ad Group Base Bid CPM',
                            'Creative Name',
                            'Bids',
                            'Bid Amount',
                            'Imps',
                            'Clicks',
                            'PC 1',
                            'PC 2',
                            'PC 3',
                            'PC 4',
                            'PC 5',
                            'PC 6',
                            'PI 1',
                            'PI 2',
                            'PI 3',
                            'PI 4',
                            'PI 5',
                            'PI 6',
                            'PC 1 Rev',
                            'PC 2 Rev',
                            'PC 3 Rev',
                            'PC 4 Rev',
                            'PC 5 Rev',
                            'PC 6 Rev',
                            'PI 1 Rev',
                            'PI 2 Rev',
                            'PI 3 Rev',
                            'PI 4 Rev',
                            'PI 5 Rev',
                            'PI 6 Rev',
                            'Advertiser Total Cost',
                            'VideoEventCreativeView',
                            'VideoEventStart',
                            'VideoEventFirstQuarter',
                            'VideoEventMidpoint',
                            'VideoEventThirdQuarter',
                            'VideoEventComplete',
                            'VideoEventMute',
                            'VideoEventUnmute',
                            'VideoEventPause',
                            'VideoEventResume',
                            'VideoEventFullscreen',
                            'VideoEventError',
                            'VideoEventSkip',
                            'VideoEventEngagedView',
                            'VideoEventRewind',
                            'VideoEventExpand',
                            'VideoEventCollapse',
                            'VideoEventClose',
                            'CTA 1',
                            'CTA 2',
                            'CTA 3',
                            'CTA 4',
                            'CTA 5',
                            'CTA 6',
                            'CTA 1 Rev',
                            'CTA 2 Rev',
                            'CTA 3 Rev',
                            'CTA 4 Rev',
                            'CTA 5 Rev',
                            'CTA 6 Rev',
                            'CreativeIsTrackable',
                            'CreativeWasViewable' ]
        self.rn_columns = ['date',
                           'advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'ad_format',
                           'creative_id',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'creative_name',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'date': postgresql.TIMESTAMP,
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'ad_format': postgresql.TEXT,
            'creative_id': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'creative_name': postgresql.TEXT,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class GeoReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Advertiser Id',
                           'Campaign Id',
                           'Ad Group Id',
                           'Country',
                           'Region',
                           'Metropolitan Area',
                           'City',
                           'Advertiser Name',
                           'Campaign Name',
                           'Ad Group Name',
                           'Ad Group Budget',
                           'Ad Group Daily Target',
                           'Ad Group Daily Cap',
                           'Ad Group Base Bid CPM',
                           'Bids',
                           'Bid Amount',
                           'Imps',
                           'Clicks',
                           'PC 1',
                           'PC 2',
                           'PC 3',
                           'PC 4',
                           'PC 5',
                           'PC 6',
                           'PI 1',
                           'PI 2',
                           'PI 3',
                           'PI 4',
                           'PI 5',
                           'PI 6',
                           'PC 1 Rev',
                           'PC 2 Rev',
                           'PC 3 Rev',
                           'PC 4 Rev',
                           'PC 5 Rev',
                           'PC 6 Rev',
                           'PI 1 Rev',
                           'PI 2 Rev',
                           'PI 3 Rev',
                           'PI 4 Rev',
                           'PI 5 Rev',
                           'PI 6 Rev',
                           'Advertiser Total Cost',
                           'CTA 1',
                           'CTA 2',
                           'CTA 3',
                           'CTA 4',
                           'CTA 5',
                           'CTA 6',
                           'CTA 1 Rev',
                           'CTA 2 Rev',
                           'CTA 3 Rev',
                           'CTA 4 Rev',
                           'CTA 5 Rev',
                           'CTA 6 Rev',
                           'VideoEventCreativeView',
                           'VideoEventStart',
                           'VideoEventFirstQuarter',
                           'VideoEventMidpoint',
                           'VideoEventThirdQuarter',
                           'VideoEventComplete',
                           'VideoEventMute',
                           'VideoEventUnmute',
                           'VideoEventPause',
                           'VideoEventResume',
                           'VideoEventFullscreen',
                           'VideoEventError',
                           'VideoEventSkip',
                           'VideoEventEngagedView',
                           'VideoEventRewind',
                           'VideoEventExpand',
                           'VideoEventCollapse',
                           'VideoEventClose',
                           'CreativeIsTrackable',
                           'CreativeWasViewable']
        self.rn_columns = ['advertiser_id',
                           'campaign_id',
                           'adgroup_id',
                           'country',
                           'region',
                           'metro_area',
                           'city',
                           'advertiser_name',
                           'campaign_name',
                           'adgroup_name',
                           'adgroup_budget',
                           'adgroup_daily_target',
                           'adgroup_daily_cap',
                           'adgroup_base_bid_cpm',
                           'bids',
                           'bid_amount',
                           'impressions',
                           'clicks',
                           'ctc_1',
                           'ctc_2',
                           'ctc_3',
                           'ctc_4',
                           'ctc_5',
                           'ctc_6',
                           'vtc_1',
                           'vtc_2',
                           'vtc_3',
                           'vtc_4',
                           'vtc_5',
                           'vtc_6',
                           'ctc_1_rev',
                           'ctc_2_rev',
                           'ctc_3_rev',
                           'ctc_4_rev',
                           'ctc_5_rev',
                           'ctc_6_rev',
                           'vtc_1_rev',
                           'vtc_2_rev',
                           'vtc_3_rev',
                           'vtc_4_rev',
                           'vtc_5_rev',
                           'vtc_6_rev',
                           'cost',
                           'cta_1',
                           'cta_2',
                           'cta_3',
                           'cta_4',
                           'cta_5',
                           'cta_6',
                           'cta_1_rev',
                           'cta_2_rev',
                           'cta_3_rev',
                           'cta_4_rev',
                           'cta_5_rev',
                           'cta_6_rev',
                           'vid_creative_view',
                           'vid_start',
                           'vid_first_quarter',
                           'vid_midpoint',
                           'vid_third_quarter',
                           'vid_complete',
                           'vid_mute',
                           'vid_unmute',
                           'vid_pause',
                           'vid_resume',
                           'vid_fullscreen',
                           'vid_error',
                           'vid_skip',
                           'vid_engaged_view',
                           'vid_rewind',
                           'vid_expand',
                           'vid_collapse',
                           'vid_close',
                           'creative_is_trackable',
                           'creative_was_viewable']
        self.dtype = {
            'advertiser_id': postgresql.TEXT,
            'campaign_id': postgresql.TEXT,
            'adgroup_id': postgresql.TEXT,
            'country': postgresql.TEXT,
            'region': postgresql.TEXT,
            'metro_area': postgresql.TEXT,
            'city': postgresql.TEXT,
            'advertiser_name': postgresql.TEXT,
            'campaign_name': postgresql.TEXT,
            'adgroup_name': postgresql.TEXT,
            'adgroup_budget': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_target': postgresql.DOUBLE_PRECISION,
            'adgroup_daily_cap': postgresql.DOUBLE_PRECISION,
            'adgroup_base_bid_cpm': postgresql.DOUBLE_PRECISION,
            'bids': postgresql.BIGINT,
            'bid_amount': postgresql.DOUBLE_PRECISION,
            'impressions': postgresql.BIGINT,
            'clicks': postgresql.BIGINT,
            'ctc_1': postgresql.BIGINT,
            'ctc_2': postgresql.BIGINT,
            'ctc_3': postgresql.BIGINT,
            'ctc_4': postgresql.BIGINT,
            'ctc_5': postgresql.BIGINT,
            'ctc_6': postgresql.BIGINT,
            'vtc_1': postgresql.BIGINT,
            'vtc_2': postgresql.BIGINT,
            'vtc_3': postgresql.BIGINT,
            'vtc_4': postgresql.BIGINT,
            'vtc_5': postgresql.BIGINT,
            'vtc_6': postgresql.BIGINT,
            'ctc_1_rev': postgresql.DOUBLE_PRECISION,
            'ctc_2_rev': postgresql.DOUBLE_PRECISION,
            'ctc_3_rev': postgresql.DOUBLE_PRECISION,
            'ctc_4_rev': postgresql.DOUBLE_PRECISION,
            'ctc_5_rev': postgresql.DOUBLE_PRECISION,
            'ctc_6_rev': postgresql.DOUBLE_PRECISION,
            'vtc_1_rev': postgresql.DOUBLE_PRECISION,
            'vtc_2_rev': postgresql.DOUBLE_PRECISION,
            'vtc_3_rev': postgresql.DOUBLE_PRECISION,
            'vtc_4_rev': postgresql.DOUBLE_PRECISION,
            'vtc_5_rev': postgresql.DOUBLE_PRECISION,
            'vtc_6_rev': postgresql.DOUBLE_PRECISION,
            'cost': postgresql.DOUBLE_PRECISION,
            'cta_1': postgresql.BIGINT,
            'cta_2': postgresql.BIGINT,
            'cta_3': postgresql.BIGINT,
            'cta_4': postgresql.BIGINT,
            'cta_5': postgresql.BIGINT,
            'cta_6': postgresql.BIGINT,
            'cta_1_rev': postgresql.DOUBLE_PRECISION,
            'cta_2_rev': postgresql.DOUBLE_PRECISION,
            'cta_3_rev': postgresql.DOUBLE_PRECISION,
            'cta_4_rev': postgresql.DOUBLE_PRECISION,
            'cta_5_rev': postgresql.DOUBLE_PRECISION,
            'cta_6_rev': postgresql.DOUBLE_PRECISION,
            'vid_creative_view': postgresql.BIGINT,
            'vid_start': postgresql.BIGINT,
            'vid_first_quarter': postgresql.BIGINT,
            'vid_midpoint': postgresql.BIGINT,
            'vid_third_quarter': postgresql.BIGINT,
            'vid_complete': postgresql.BIGINT,
            'vid_mute': postgresql.BIGINT,
            'vid_unmute': postgresql.BIGINT,
            'vid_pause': postgresql.BIGINT,
            'vid_resume': postgresql.BIGINT,
            'vid_fullscreen': postgresql.BIGINT,
            'vid_error': postgresql.BIGINT,
            'vid_skip': postgresql.BIGINT,
            'vid_engaged_view': postgresql.BIGINT,
            'vid_rewind': postgresql.BIGINT,
            'vid_expand': postgresql.BIGINT,
            'vid_collapse': postgresql.BIGINT,
            'vid_close': postgresql.BIGINT,
            'creative_is_trackable': postgresql.BIGINT,
            'creative_was_viewable': postgresql.BIGINT
        }

class ConversionReport(Report):

    def __init__(self, filename):
        Report.__init__(self, filename)

        self.og_columns = ['Conversion Time',
                           'TDID',
                           'Conversion Id',
                           'Order Id',
                           '# Impressions',
                           '# Display Clicks',
                           '# Ad Groups w/ Activity',
                           '# Frequency Cycles and Ad Groups w/ Activity',
                           '# Frequency Cycles and Ad Groups Where FCap is Reached',
                           'Conversion Type',
                           'Tracking Tag Name',
                           'Referrer Url',
                           'Path to Conversion',
                           'Monetary Value',
                           'First Impression Time',
                           'First Impression Campaign Id',
                           'First Impression Campaign Name',
                           'First Impression Ad Group Id',
                           'First Impression Ad Group Name',
                           'First Impression Creative Id',
                           'First Impression Creative Name',
                           'First Impression Format',
                           'Last Impression Time',
                           'Last Impression Campaign Id',
                           'Last Impression Campaign Name',
                           'Last Impression Ad Group Id',
                           'Last Impression Ad Group Name',
                           'Last Impression Creative Id',
                           'Last Impression Creative Name',
                           'Last Impression Format',
                           'Last Impression Frequency',
                           'Last Impression FCap',
                           'Last Impression Site',
                           'Last Impression Categories',
                           'Last Impression Country',
                           'Last Impression Region',
                           'Last Impression Metro',
                           'First Display Click Time',
                           'First Display Click Campaign Id',
                           'First Display Click Campaign Name',
                           'First Display Click Ad Group Id',
                           'First Display Click Ad Group Name',
                           'First Display Click Creative Id',
                           'First Display Click Creative Name',
                           'First Display Click Format',
                           'Last Display Click Time',
                           'Last Display Click Campaign Id',
                           'Last Display Click Campaign Name',
                           'Last Display Click Ad Group Id',
                           'Last Display Click Ad Group Name',
                           'Last Display Click Creative Id',
                           'Last Display Click Creative Name',
                           'Last Display Click Format',
                           'Advertiser Id']
        self.rn_columns = ['conversion_time',
                           'tdid',
                           'conversion_id',
                           'order_id',
                           'num_of_impressions',
                           'num_of_display_clicks',
                           'num_adgroups_w_activity',
                           'num_freq_cycles_and_adgroups_w_activity',
                           'num_freq_cycles_and_adgroups_when_fcap_reached',
                           'conversion_type',
                           'tracking_tag_name',
                           'referrer_url',
                           'path_to_conversion',
                           'monetary_value',
                           'first_imp_time',
                           'first_imp_campaign_id',
                           'first_imp_campaign_name',
                           'first_imp_adgroup_id',
                           'first_imp_adgroup_name',
                           'first_imp_creative_id',
                           'first_imp_creative_name',
                           'first_imp_format',
                           'last_imp_time',
                           'last_imp_campaign_id',
                           'last_imp_campaign_name',
                           'last_imp_adgroup_id',
                           'last_imp_adgroup_name',
                           'last_imp_creative_id',
                           'last_imp_creative_name',
                           'last_imp_format',
                           'last_imp_frequency',
                           'last_imp_fcap',
                           'last_imp_site',
                           'last_imp_categories',
                           'last_imp_country',
                           'last_imp_region',
                           'last_imp_metro',
                           'first_click_time',
                           'first_click_campaign_id',
                           'first_click_campaign_name',
                           'first_click_adgroup_id',
                           'first_click_adgroup_name',
                           'first_click_creative_id',
                           'first_click_creative_name',
                           'first_click_format',
                           'last_click_time',
                           'last_click_campaign_id',
                           'last_click_campaign_name',
                           'last_click_adgroup_id',
                           'last_click_adgroup_name',
                           'last_click_creative_id',
                           'last_click_creative_name',
                           'last_click_format',
                           'advertiser_id']
        self.dtype = {
            'conversion_time': postgresql.TIMESTAMP,
            'tdid': postgresql.TEXT,
            'conversion_id': postgresql.TEXT,
            'order_id': postgresql.TEXT,
            'num_of_impressions': postgresql.BIGINT,
            'num_of_display_clicks': postgresql.BIGINT,
            'num_of_adgroups_w_activity': postgresql.BIGINT,
            'num_freq_cycles_and_adgroups_w_activity': postgresql.BIGINT,
            'num_freq_cycles_and_adgroups_when_fcap_reached': postgresql.BIGINT,
            'conversion_type': postgresql.TEXT,
            'tracking_tag_name': postgresql.TEXT,
            'referrer_url': postgresql.TEXT,
            'path_to_conversion': postgresql.TEXT,
            'monetary_value': postgresql.DOUBLE_PRECISION,
            'first_imp_time': postgresql.TIMESTAMP,
            'first_imp_campaign_id': postgresql.TEXT,
            'first_imp_campaign_name': postgresql.TEXT,
            'first_imp_adgroup_id': postgresql.TEXT,
            'first_imp_adgroup_name': postgresql.TEXT,
            'first_imp_creative_id': postgresql.TEXT,
            'first_imp_creative_name': postgresql.TEXT,
            'first_imp_format': postgresql.TEXT,
            'last_imp_time': postgresql.TIMESTAMP,
            'last_imp_campaign_id': postgresql.TEXT,
            'last_imp_campaign_name': postgresql.TEXT,
            'last_imp_adgroup_id': postgresql.TEXT,
            'last_imp_adgroup_name': postgresql.TEXT,
            'last_imp_creative_id': postgresql.TEXT,
            'last_imp_creative_name': postgresql.TEXT,
            'last_imp_format': postgresql.TEXT,
            'last_imp_frequency': postgresql.BIGINT,
            'last_imp_fcap': postgresql.TEXT,
            'last_imp_site': postgresql.TEXT,
            'last_imp_categories': postgresql.TEXT,
            'last_imp_country': postgresql.TEXT,
            'last_imp_region': postgresql.TEXT,
            'last_imp_metro': postgresql.TEXT,
            'first_click_time': postgresql.TIMESTAMP,
            'first_click_campaign_id': postgresql.TEXT,
            'first_click_campaign_name': postgresql.TEXT,
            'first_click_adgroup_id': postgresql.TEXT,
            'first_click_adgroup_name': postgresql.TEXT,
            'first_click_creative_id': postgresql.TEXT,
            'first_click_creative_name': postgresql.TEXT,
            'first_click_format': postgresql.TEXT,
            'last_click_time': postgresql.TIMESTAMP,
            'last_click_campaign_id': postgresql.TEXT,
            'last_click_campaign_name': postgresql.TEXT,
            'last_click_adgroup_id': postgresql.TEXT,
            'last_click_adgroup_name': postgresql.TEXT,
            'last_click_creative_id': postgresql.TEXT,
            'last_click_creative_name': postgresql.TEXT,
            'last_click_format': postgresql.TEXT,
            'advertiser_id': postgresql.TEXT
        }


def parse_filename(filename):
    # Parse the filename for all metadata
    if "1 Day" in filename:
        regex = re.compile(r'.*Advertiser - (?P<advertiser>.*) - (?P<advertiser_id>\w{7}) - (RTB )?(?P<report_type>.*)'
                           r' - (?P<report_length>1 Day) - USD - (?P<report_start_date>\d{8})\.tsv$')

    elif "7 Days" in filename:
        regex = re.compile(r'.*Advertiser - (?P<advertiser>.*) - (?P<advertiser_id>\w{7}) - (RTB )?(?P<report_type>.*)'
                           r' - (?P<report_length>\d{1,2} Days) - USD - (?P<report_start_date>\d{8})-'
                           r'(?P<report_end_date>\d{8})\.tsv$')

    elif "30 Days" in filename:
        regex = re.compile(r'.*Advertiser - (?P<advertiser>.*) - (?P<advertiser_id>\w{7}) - (RTB )?(?P<report_type>.*)'
                           r' - (?P<report_length>\d{1,2} Days) - USD - (?P<report_start_date>\d{8})-'
                           r'(?P<report_end_date>\d{8})\.tsv$')

    match = regex.match(filename)

    if match:
        file_info = match.groupdict()
        file_info['filename'] = filename

        # 1 Day reports don't have an end date, so this just sets it to the start date
        try:
            file_info['report_end_date'] = datetime.strptime(file_info['report_end_date'], '%Y%m%d')
        except KeyError:
            file_info['report_end_date'] = datetime.strptime(file_info['report_start_date'], '%Y%m%d')

        file_info['report_start_date'] = datetime.strptime(file_info['report_start_date'], '%Y%m%d')

        return file_info
    else:
        print "Unexpected file type or name: " + filename


def report_filter(reports, **view):
    # TODO: 1 - Implement unit testing for this function

    # Filter reports by: Type
    reports = [r for r in reports if r.report_type == view['report_type']]

    # Filter reports by: Advertiser
    if view['advertiser'] is not None:
        reports = [r for r in reports if r.advertiser_id in view['advertiser']]

    # Filter reports by: Date Range
    filtered_list = []
    if view['date_range'] is not None:
        for r in reports:
            now = datetime.now()
            delta = now - r.end_date

            if int(delta.days) <= view['date_range']:
                # TODO: 3 - This should eventually become the basis of logging
                #print r.filename + " " + str(delta.days)
                filtered_list.append(r)

        reports = filtered_list
    return reports